### PR TITLE
Add support for 'rows' mode

### PR DESCRIPTION
**Pull request by jwmcglynn**
Allow specifying data as a list of rows instead of columns by specifying
the 'rows' flag:

- rows nosum
  - Header 1
    - Header 2
  - Shows up under Header 1
    - Shows up under Header 2

With this flag, tables operate in a similar way to the Roam Research
`{{table}}` macro.

### CODE REVIEW

**Comment by jwmcglynn** [comment]
Here's a screencast of the behavior in action.

Rows screencast

**Review by benjypng — CHANGES_REQUESTED** [review]
Hi! Thanks for the PR.
To make it more maintainable, I've gone ahead to separate the two scenarios into two separate functions.

If possible, could you insert your code under childBlocksAsColumns.js so that it returns a different `data` and `columns` that can be inserted into `App.jsx`?

Thanks for the consideration!

**Comment by jwmcglynn** [comment]
No problem, done!

I also took the liberty to include the screencast in the README, and include two other small changes:
* Changed `App.jsx` to use ES6 destructuring and a ternary, to avoid calling the `blocksAsColumns` or `childBlocksAsColumns` function twice.
* Fix runtime errors in `blocksAsColumns` for partially-typed tables.

If you don't want either of these or want me to split them into separate PRs, please let me know.

**Comment by hkgnp** [comment]
Looks good! Thanks for your wonderful addition!

**Review by benjypng — COMMENTED** [review]
Looks good! Thanks for your wonderful addition!

**Pull request merged**
